name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS]
        include:
          - os: macOS
            flutter_path: ~/actions-runner/_work/_tool/flutter/
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
  build:
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      matrix:
        os: [macOS]
        include:
          - os: macOS
            flutter_path: ~/actions-runner/_work/_tool/flutter/
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Flutter Pub get
        run: flutter pub get

      - name: Flutter Build web app
        run: flutter build web --base-href /${{ github.event.repository.name }}/ --release

      - name: Check for Symlinks
        run: find build/web -type l
        continue-on-error: true

      - name: Check Artifact Size
        run: du -sh build/web
        
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifacts
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            build/web/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: Linux
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
