name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Required for - name: Cache node modules
        
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v4
        env:
          cache-name: cache-pub-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.pub-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true

      - name: Flutter Install dependencies
        run: flutter pub get

      - name: Flutter Build web app
        run: flutter build web --base-href /${{ github.event.repository.name }}/ --release

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: |
            build/web/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4